name: Tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tox tests in docker compose environment
      run: docker compose up --build
