name: Tests
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Start opensearch in a docker container
      run: |
        docker compose up --build -d opensearch
    - name: Test with pytest
      run: |
        export OPENSEARCH_HOST=localhost
        export OPENSEARCH_USER=admin
        export OPENSEARCH_PASSWORD=admin
        export OPENSEARCH_PORT=9200
        export PYTHONPATH=/flask_opensearch
        pytest -vvv
